export const LABEL_CONSTANT = {
  registrati_title: "Registrati",
  reimposta_password: "Reimposta Password",
  insert_dati_registrazione: "Inserisci i dati richiesti per la registrazione.",
  insert_dati_reimposta_pass: "Inserisci la tua email per recuperare la password.",
  indietro: "Indietro",
  avanti: "Avanti",
  inviaEmail: "Invia Email",
  verifica_email: "Verifica Email",
  verificare_password: "verificare l'account",
  recuperare_password: "recuperare la password",
  nuova_password: "Nuova Password",
  seleziona_nuova_password: "Scegli una nuova password per accedere al tuo account.",
  link_scaduto: "Link Scaduto",
  link_non_valido: "Ci dispiace, ma questo link non è più valido.",
  carica_file: "Carica File",
  inserisci_dati_anagrafici: "Inserisci i tuoi dati anagrafici" ,
  email_inviata: "Email inviata correttamente" ,
  registrazione_completata: "Registrazione effettuata correttamente",
  credenziali:"Credenziali",
  insert_credenziali:"Inserisci le tue credenziali d'accesso",
  squadra:"Squadra",
  insert_squadra: "Scegli squadra e categoria a cui sei associato",
  riepilogo:"Riepilogo",
  verifica_riepilogo:"Verifica i dati che hai inserito",
  insert_dati_registrazione_step_1:"Inserisci i tuoi dati anagrafici",
  
};
